---
functional:
  - Пользователь должен иметь возможность на странице товара и в каталоге ознакомиться с названием, рейтингом, и ценой со скидкой и без нее. 
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины. Корзина будет хранится в сессии браузера. 
  - Пользователь должен иметь возможность на странице корзины удалять товар из корзины
  - Пользователь должен иметь возможность продолжить выбирать товары в каталоге
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
implicit:
  - Пользователь должен иметь возможность переключать цену товара в российский рубль
  - Пользоватьель должен иметь возможность при добавлении товара в корзину указывать количество товара
  - Пользоватьель должен иметь возможность редактировать количество товара в корзине
  - Изображения в каталоге товаров не должны растягиваться, деформироваться
  - Цена не должна быть отрицательной
