---
functional:
  - На странице корзины пользователь cможет удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты. Корзина будет хранится в сессии браузера.
  - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее. Пользователь будет добавлять товар в корзину и продолжать выбирать товары в каталоге.
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
implicit:
  - Пользователь должен иметь возможность переключать цену товара в российский рубль
  - Пользоватьель должен иметь возможность при добавлении товара в корзину указывать количество товара
  - Пользоватьель должен иметь возможность редактировать количество товара в корзине
  - Изображения в каталоге товаров не должны растягиваться, деформироваться
  - Цена не должна быть отрицательной
